# This file was automatically generated by SWIG (https://www.swig.org).
# Version 4.1.0
#
# Do not make changes to this file unless you know what you are doing - modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
if __import__('os').name == 'nt': import win32api; win32api.LoadLibrary('HelloWorld.dll')
if __package__ or '.' in __name__:
    from . import _HelloWorldWrapper
else:
    import _HelloWorldWrapper

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_instance_variable(set):
    def set_instance_attr(self, name, value):
        if name == "this":
            set(self, name, value)
        elif name == "thisown":
            self.this.own(value)
        elif hasattr(self, name) and isinstance(getattr(type(self), name), property):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add instance attributes to %s" % self)
    return set_instance_attr


def _swig_setattr_nondynamic_class_variable(set):
    def set_class_attr(cls, name, value):
        if hasattr(cls, name) and not isinstance(getattr(cls, name), property):
            set(cls, name, value)
        else:
            raise AttributeError("You cannot add class attributes to %s" % cls)
    return set_class_attr


def _swig_add_metaclass(metaclass):
    """Class decorator for adding a metaclass to a SWIG wrapped class - a slimmed down version of six.add_metaclass"""
    def wrapper(cls):
        return metaclass(cls.__name__, cls.__bases__, cls.__dict__.copy())
    return wrapper


class _SwigNonDynamicMeta(type):
    """Meta class to enforce nondynamic attributes (no new attributes) for a class"""
    __setattr__ = _swig_setattr_nondynamic_class_variable(type.__setattr__)


class SwigPyIterator(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _HelloWorldWrapper.delete_SwigPyIterator

    def value(self):
        return _HelloWorldWrapper.SwigPyIterator_value(self)

    def incr(self, n=1):
        return _HelloWorldWrapper.SwigPyIterator_incr(self, n)

    def decr(self, n=1):
        return _HelloWorldWrapper.SwigPyIterator_decr(self, n)

    def distance(self, x):
        return _HelloWorldWrapper.SwigPyIterator_distance(self, x)

    def equal(self, x):
        return _HelloWorldWrapper.SwigPyIterator_equal(self, x)

    def copy(self):
        return _HelloWorldWrapper.SwigPyIterator_copy(self)

    def next(self):
        return _HelloWorldWrapper.SwigPyIterator_next(self)

    def __next__(self):
        return _HelloWorldWrapper.SwigPyIterator___next__(self)

    def previous(self):
        return _HelloWorldWrapper.SwigPyIterator_previous(self)

    def advance(self, n):
        return _HelloWorldWrapper.SwigPyIterator_advance(self, n)

    def __eq__(self, x):
        return _HelloWorldWrapper.SwigPyIterator___eq__(self, x)

    def __ne__(self, x):
        return _HelloWorldWrapper.SwigPyIterator___ne__(self, x)

    def __iadd__(self, n):
        return _HelloWorldWrapper.SwigPyIterator___iadd__(self, n)

    def __isub__(self, n):
        return _HelloWorldWrapper.SwigPyIterator___isub__(self, n)

    def __add__(self, n):
        return _HelloWorldWrapper.SwigPyIterator___add__(self, n)

    def __sub__(self, *args):
        return _HelloWorldWrapper.SwigPyIterator___sub__(self, *args)
    def __iter__(self):
        return self

# Register SwigPyIterator in _HelloWorldWrapper:
_HelloWorldWrapper.SwigPyIterator_swigregister(SwigPyIterator)
FASTCDR_VERSION_MAJOR = _HelloWorldWrapper.FASTCDR_VERSION_MAJOR
FASTCDR_VERSION_MINOR = _HelloWorldWrapper.FASTCDR_VERSION_MINOR
FASTCDR_VERSION_MICRO = _HelloWorldWrapper.FASTCDR_VERSION_MICRO
FASTCDR_VERSION_STR = _HelloWorldWrapper.FASTCDR_VERSION_STR
HAVE_CXX11 = _HelloWorldWrapper.HAVE_CXX11
FASTCDR_IS_BIG_ENDIAN_TARGET = _HelloWorldWrapper.FASTCDR_IS_BIG_ENDIAN_TARGET
FASTCDR_HAVE_FLOAT128 = _HelloWorldWrapper.FASTCDR_HAVE_FLOAT128
FASTCDR_SIZEOF_LONG_DOUBLE = _HelloWorldWrapper.FASTCDR_SIZEOF_LONG_DOUBLE
import fastdds
class _TimeSeq(fastdds.LoanableCollection):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _HelloWorldWrapper.delete__TimeSeq

# Register _TimeSeq in _HelloWorldWrapper:
_HelloWorldWrapper._TimeSeq_swigregister(_TimeSeq)
class TimeSeq(_TimeSeq):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    __swig_destroy__ = _HelloWorldWrapper.delete_TimeSeq

    def __init__(self, *args):
        _HelloWorldWrapper.TimeSeq_swiginit(self, _HelloWorldWrapper.new_TimeSeq(*args))

    def __len__(self):
        return _HelloWorldWrapper.TimeSeq___len__(self)

    def __getitem__(self, i):
        return _HelloWorldWrapper.TimeSeq___getitem__(self, i)

# Register TimeSeq in _HelloWorldWrapper:
_HelloWorldWrapper.TimeSeq_swigregister(TimeSeq)
class Time(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    __swig_destroy__ = _HelloWorldWrapper.delete_Time

    def __init__(self, *args):
        _HelloWorldWrapper.Time_swiginit(self, _HelloWorldWrapper.new_Time(*args))

    def __eq__(self, x):
        return _HelloWorldWrapper.Time___eq__(self, x)

    def __ne__(self, x):
        return _HelloWorldWrapper.Time___ne__(self, x)

    def sec(self, *args):
        return _HelloWorldWrapper.Time_sec(self, *args)

    def nanosec(self, *args):
        return _HelloWorldWrapper.Time_nanosec(self, *args)

# Register Time in _HelloWorldWrapper:
_HelloWorldWrapper.Time_swigregister(Time)
FASTDDS_GEN_API_VER = _HelloWorldWrapper.FASTDDS_GEN_API_VER
class TimePubSubType(fastdds.TopicDataType):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _HelloWorldWrapper.TimePubSubType_swiginit(self, _HelloWorldWrapper.new_TimePubSubType())
    __swig_destroy__ = _HelloWorldWrapper.delete_TimePubSubType

    def serialize(self, data, payload, data_representation):
        return _HelloWorldWrapper.TimePubSubType_serialize(self, data, payload, data_representation)

    def deserialize(self, payload, data):
        return _HelloWorldWrapper.TimePubSubType_deserialize(self, payload, data)

    def calculate_serialized_size(self, data, data_representation):
        return _HelloWorldWrapper.TimePubSubType_calculate_serialized_size(self, data, data_representation)

    def compute_key(self, *args):
        return _HelloWorldWrapper.TimePubSubType_compute_key(self, *args)

    def create_data(self):
        return _HelloWorldWrapper.TimePubSubType_create_data(self)

    def delete_data(self, data):
        return _HelloWorldWrapper.TimePubSubType_delete_data(self, data)

    def register_type_object_representation(self):
        return _HelloWorldWrapper.TimePubSubType_register_type_object_representation(self)

    def is_bounded(self):
        return _HelloWorldWrapper.TimePubSubType_is_bounded(self)

    def is_plain(self, data_representation):
        return _HelloWorldWrapper.TimePubSubType_is_plain(self, data_representation)

    def construct_sample(self, memory):
        return _HelloWorldWrapper.TimePubSubType_construct_sample(self, memory)

# Register TimePubSubType in _HelloWorldWrapper:
_HelloWorldWrapper.TimePubSubType_swigregister(TimePubSubType)
class _HeaderSeq(fastdds.LoanableCollection):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _HelloWorldWrapper.delete__HeaderSeq

# Register _HeaderSeq in _HelloWorldWrapper:
_HelloWorldWrapper._HeaderSeq_swigregister(_HeaderSeq)
class HeaderSeq(_HeaderSeq):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    __swig_destroy__ = _HelloWorldWrapper.delete_HeaderSeq

    def __init__(self, *args):
        _HelloWorldWrapper.HeaderSeq_swiginit(self, _HelloWorldWrapper.new_HeaderSeq(*args))

    def __len__(self):
        return _HelloWorldWrapper.HeaderSeq___len__(self)

    def __getitem__(self, i):
        return _HelloWorldWrapper.HeaderSeq___getitem__(self, i)

# Register HeaderSeq in _HelloWorldWrapper:
_HelloWorldWrapper.HeaderSeq_swigregister(HeaderSeq)
class Header(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    __swig_destroy__ = _HelloWorldWrapper.delete_Header

    def __init__(self, *args):
        _HelloWorldWrapper.Header_swiginit(self, _HelloWorldWrapper.new_Header(*args))

    def __eq__(self, x):
        return _HelloWorldWrapper.Header___eq__(self, x)

    def __ne__(self, x):
        return _HelloWorldWrapper.Header___ne__(self, x)

    def stamp(self, *args):
        return _HelloWorldWrapper.Header_stamp(self, *args)

    def frame_id(self, *args):
        return _HelloWorldWrapper.Header_frame_id(self, *args)

# Register Header in _HelloWorldWrapper:
_HelloWorldWrapper.Header_swigregister(Header)
class HeaderPubSubType(fastdds.TopicDataType):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _HelloWorldWrapper.HeaderPubSubType_swiginit(self, _HelloWorldWrapper.new_HeaderPubSubType())
    __swig_destroy__ = _HelloWorldWrapper.delete_HeaderPubSubType

    def serialize(self, data, payload, data_representation):
        return _HelloWorldWrapper.HeaderPubSubType_serialize(self, data, payload, data_representation)

    def deserialize(self, payload, data):
        return _HelloWorldWrapper.HeaderPubSubType_deserialize(self, payload, data)

    def calculate_serialized_size(self, data, data_representation):
        return _HelloWorldWrapper.HeaderPubSubType_calculate_serialized_size(self, data, data_representation)

    def compute_key(self, *args):
        return _HelloWorldWrapper.HeaderPubSubType_compute_key(self, *args)

    def create_data(self):
        return _HelloWorldWrapper.HeaderPubSubType_create_data(self)

    def delete_data(self, data):
        return _HelloWorldWrapper.HeaderPubSubType_delete_data(self, data)

    def register_type_object_representation(self):
        return _HelloWorldWrapper.HeaderPubSubType_register_type_object_representation(self)

    def is_bounded(self):
        return _HelloWorldWrapper.HeaderPubSubType_is_bounded(self)

    def is_plain(self, data_representation):
        return _HelloWorldWrapper.HeaderPubSubType_is_plain(self, data_representation)

    def construct_sample(self, memory):
        return _HelloWorldWrapper.HeaderPubSubType_construct_sample(self, memory)

# Register HeaderPubSubType in _HelloWorldWrapper:
_HelloWorldWrapper.HeaderPubSubType_swigregister(HeaderPubSubType)
class int32_t_2_array(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def iterator(self):
        return _HelloWorldWrapper.int32_t_2_array_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _HelloWorldWrapper.int32_t_2_array___nonzero__(self)

    def __bool__(self):
        return _HelloWorldWrapper.int32_t_2_array___bool__(self)

    def __len__(self):
        return _HelloWorldWrapper.int32_t_2_array___len__(self)

    def __getslice__(self, i, j):
        return _HelloWorldWrapper.int32_t_2_array___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _HelloWorldWrapper.int32_t_2_array___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _HelloWorldWrapper.int32_t_2_array___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _HelloWorldWrapper.int32_t_2_array___delitem__(self, *args)

    def __getitem__(self, *args):
        return _HelloWorldWrapper.int32_t_2_array___getitem__(self, *args)

    def __setitem__(self, *args):
        return _HelloWorldWrapper.int32_t_2_array___setitem__(self, *args)

    def __init__(self, *args):
        _HelloWorldWrapper.int32_t_2_array_swiginit(self, _HelloWorldWrapper.new_int32_t_2_array(*args))

    def empty(self):
        return _HelloWorldWrapper.int32_t_2_array_empty(self)

    def size(self):
        return _HelloWorldWrapper.int32_t_2_array_size(self)

    def swap(self, v):
        return _HelloWorldWrapper.int32_t_2_array_swap(self, v)

    def begin(self):
        return _HelloWorldWrapper.int32_t_2_array_begin(self)

    def end(self):
        return _HelloWorldWrapper.int32_t_2_array_end(self)

    def rbegin(self):
        return _HelloWorldWrapper.int32_t_2_array_rbegin(self)

    def rend(self):
        return _HelloWorldWrapper.int32_t_2_array_rend(self)

    def front(self):
        return _HelloWorldWrapper.int32_t_2_array_front(self)

    def back(self):
        return _HelloWorldWrapper.int32_t_2_array_back(self)

    def fill(self, u):
        return _HelloWorldWrapper.int32_t_2_array_fill(self, u)

    def get_buffer(self):
        return _HelloWorldWrapper.int32_t_2_array_get_buffer(self)
    __swig_destroy__ = _HelloWorldWrapper.delete_int32_t_2_array

# Register int32_t_2_array in _HelloWorldWrapper:
_HelloWorldWrapper.int32_t_2_array_swigregister(int32_t_2_array)
class _HelloWorldSeq(fastdds.LoanableCollection):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _HelloWorldWrapper.delete__HelloWorldSeq

# Register _HelloWorldSeq in _HelloWorldWrapper:
_HelloWorldWrapper._HelloWorldSeq_swigregister(_HelloWorldSeq)
class HelloWorldSeq(_HelloWorldSeq):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    __swig_destroy__ = _HelloWorldWrapper.delete_HelloWorldSeq

    def __init__(self, *args):
        _HelloWorldWrapper.HelloWorldSeq_swiginit(self, _HelloWorldWrapper.new_HelloWorldSeq(*args))

    def __len__(self):
        return _HelloWorldWrapper.HelloWorldSeq___len__(self)

    def __getitem__(self, i):
        return _HelloWorldWrapper.HelloWorldSeq___getitem__(self, i)

# Register HelloWorldSeq in _HelloWorldWrapper:
_HelloWorldWrapper.HelloWorldSeq_swigregister(HelloWorldSeq)
class HelloWorld(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    __swig_destroy__ = _HelloWorldWrapper.delete_HelloWorld

    def __init__(self, *args):
        _HelloWorldWrapper.HelloWorld_swiginit(self, _HelloWorldWrapper.new_HelloWorld(*args))

    def __eq__(self, x):
        return _HelloWorldWrapper.HelloWorld___eq__(self, x)

    def __ne__(self, x):
        return _HelloWorldWrapper.HelloWorld___ne__(self, x)

    def index(self, *args):
        return _HelloWorldWrapper.HelloWorld_index(self, *args)

    def data(self, *args):
        return _HelloWorldWrapper.HelloWorld_data(self, *args)

    def message(self, *args):
        return _HelloWorldWrapper.HelloWorld_message(self, *args)

    def header(self, *args):
        return _HelloWorldWrapper.HelloWorld_header(self, *args)

# Register HelloWorld in _HelloWorldWrapper:
_HelloWorldWrapper.HelloWorld_swigregister(HelloWorld)
class HelloWorldPubSubType(fastdds.TopicDataType):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _HelloWorldWrapper.HelloWorldPubSubType_swiginit(self, _HelloWorldWrapper.new_HelloWorldPubSubType())
    __swig_destroy__ = _HelloWorldWrapper.delete_HelloWorldPubSubType

    def serialize(self, data, payload, data_representation):
        return _HelloWorldWrapper.HelloWorldPubSubType_serialize(self, data, payload, data_representation)

    def deserialize(self, payload, data):
        return _HelloWorldWrapper.HelloWorldPubSubType_deserialize(self, payload, data)

    def calculate_serialized_size(self, data, data_representation):
        return _HelloWorldWrapper.HelloWorldPubSubType_calculate_serialized_size(self, data, data_representation)

    def compute_key(self, *args):
        return _HelloWorldWrapper.HelloWorldPubSubType_compute_key(self, *args)

    def create_data(self):
        return _HelloWorldWrapper.HelloWorldPubSubType_create_data(self)

    def delete_data(self, data):
        return _HelloWorldWrapper.HelloWorldPubSubType_delete_data(self, data)

    def register_type_object_representation(self):
        return _HelloWorldWrapper.HelloWorldPubSubType_register_type_object_representation(self)

    def is_bounded(self):
        return _HelloWorldWrapper.HelloWorldPubSubType_is_bounded(self)

    @staticmethod
    def is_zerocopy():
        return _HelloWorldWrapper.HelloWorldPubSubType_is_zerocopy()

    def is_plain(self, data_representation):
        return _HelloWorldWrapper.HelloWorldPubSubType_is_plain(self, data_representation)

    def construct_sample(self, memory):
        return _HelloWorldWrapper.HelloWorldPubSubType_construct_sample(self, memory)

# Register HelloWorldPubSubType in _HelloWorldWrapper:
_HelloWorldWrapper.HelloWorldPubSubType_swigregister(HelloWorldPubSubType)

